---

- name: Ensure script dependencies are installed
  ansible.builtin.package:
    name: '{{ repo_mirror_packages }}'
    state: present
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:installation'

- name: Ensure mirror group is present
  ansible.builtin.group:
    name: '{{ repo_mirror_group }}'
    state: present
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:installation'

- name: Ensure mirror user is present
  ansible.builtin.user:
    name: '{{ repo_mirror_user }}'
    state: present
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:installation'

- name: Ensure mirror directories are present
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
    owner: "{{ repo_mirror_user }}"
    group: "{{ repo_mirror_group }}"
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:installation'
  with_items:
    - '{{ repo_mirror_base_path }}'
    - '{{ repo_mirror_tmp_path }}'
    - '{{ repo_mirror_log_path }}'

- name: Create landingpage folder
  ansible.builtin.file:
    path: '{{ repo_mirror_landingpage_clone_dir }}'
    state: directory
    mode: "0755"
  check_mode: false
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:configuration'
    - 'role::repo_mirror:configuration:landingpage'

- name: Clone landingpage repository  # noqa: latest[git]
  ansible.builtin.git:
    repo: https://github.com/adfinis/landingpage-repo_mirror
    dest: '{{ repo_mirror_landingpage_clone_dir }}'
    force: true
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:configuration'
    - 'role::repo_mirror:configuration:landingpage'

- name: Run yarn and let yarn install the dependencies for yarn
  ansible.builtin.command:
    cmd: yarnpkg
    chdir: '{{ repo_mirror_landingpage_clone_dir }}'
  changed_when: false
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:configuration'
    - 'role::repo_mirror:configuration:landingpage'

- name: Build landingpage
  ansible.builtin.command:
    cmd: make prod
    chdir: '{{ repo_mirror_landingpage_clone_dir }}'
  changed_when: false
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:configuration'
    - 'role::repo_mirror:configuration:landingpage'

- name: Set correct permissions
  ansible.builtin.file:
    recurse: true
    group: www-data
    owner: www-data
    path: '{{ repo_mirror_landingpage_clone_dir }}/dist/'
  when: not ansible_check_mode
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:configuration'
    - 'role::repo_mirror:configuration:landingpage'

- name: Deploy landingpage
  ansible.posix.synchronize:
    dest: '{{ repo_mirror_www_path }}/'
    src: '{{ repo_mirror_landingpage_clone_dir }}/dist/'
    group: true
    owner: true
  delegate_to: "{{ inventory_hostname }}"
  when: not ansible_check_mode
  tags:
    - 'role::repo_mirror'
    - 'role::repo_mirror:configuration'
    - 'role::repo_mirror:configuration:landingpage'
